# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84cf50ffa4d57e1091d5df32508e1dd12cf3c323e7e97344678b62877b43f7ef0d70152fa929a1787145211fa82649b787098a1e4379156ed3725269ddcd6dc9

test:
  secret_key_base: 06b01a9c86927a45b3596eedca476f5bf2b55af8ca144a428413333ed730db713b26f054d5097238584888dc5673d0b15580e20a7d940dd429d7f855c48b2b13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
